remote_theme : mmistakes/minimal-mistakes
title: Galaxy NGC 891
include: ["_pages"]
author_profile: true 

author: 
  name: "Jane Doe"
  avatar: "http://somedomain.com/path/to/pic.jpg"
  bio: "Hello."
  
